steps:
  - label: ":hammer: Setup"
    key: setup
    command:
      - echo "Preparing dummy environment..."
      - echo "Dependencies installed successfully"
  
  - label: "Record Buildkite cluster"
    key: record-cluster
    command:
      - buildkite-agent meta-data set \
          "dd_tags.buildkite_cluster_id" \
          "$BUILDKITE_CLUSTER_ID"
    

  - label: ":test_tube: Run tests"
    key: test
    command: echo "Running dummy tests..." && exit 0
    depends_on: ["setup"]

  - label: ":rocket: Deploy"
    command: echo "Deploying dummy application..." && exit 0
    depends_on: ["test"]
    branches: "main"
